#!/bin/bash

function run(){
    docker build --tag babyfoot . &&
    docker run --rm -it --name babyfoot \
    --volume $(pwd):/home/babyfoot \
    babyfoot
}

function build(){
    docker build --tag babyfoot .
}

function start(){
    docker run --rm -it --name babyfoot \
    --volume $(pwd):/home/babyfoot \
    babyfoot
}

"$@"