version: '2'
services:
  builder:
    container_name: babyfoot
    build: .
    image: babyfoot
    volumes:
      - ".:/home/babyfoot"
      - $HOME/.Xauthority:/root/.Xauthority:rw
    command: tail -f /dev/null
    network_mode: host
    environment:
      - DISPLAY