#!/bin/bash

function build(){
    docker build --tag babyfoot .
}

function start(){
    docker run --rm -it --name babyfoot \
    --volume $(pwd):/home/babyfoot \
    babyfoot
}

function cmake(){
    docker run --rm --name babyfoot \
    --volume $(pwd):/home/babyfoot \
    --workdir="/home/babyfoot/build" \
    babyfoot \
    cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/x86_64-w64-mingw32.cmake -DCMAKE_BUILD_TYPE=Debug
}

function make(){
    docker run --rm --name babyfoot \
    --volume $(pwd):/home/babyfoot \
    --workdir="/home/babyfoot/build" \
    babyfoot \
    make -j6
}

"$@"